
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reading-bot
  labels:
    app: reading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reading-bot
  template:
    metadata:
      labels:
        app: reading-bot
    spec:
      containers:
        - name: reading-bot
          image: ghcr.io/yourusername/reading-bot:latest
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: DATABASE_URL
          ports:
            - containerPort: 8000  # Adjust as needed
      imagePullSecrets:
        - name: ghcr-secret
