apiVersion: v1
kind: Service
metadata:
  name: reading-bot-service
spec:
  selector:
    app: reading-bot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Adjust as needed
  type: LoadBalancer  # Use appropriate service type
