
# .github/workflows/cd.yml
name: CD for Telegram Reading List Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: set up kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: deploy to kubernetes
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}
        run: |
          helm upgrade --install kerhoff-reading-list-bot ./deploy/helm/kerhoff-reading-list-bot \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest \
            --set env.DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} \
            --set env.TELEGRAM_BOT_TOKEN=${{ secrets.PROD_TELEGRAM_BOT_TOKEN }}

