# .github/workflows/ci.yml
name: CI/CD for Telegram Reading List Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: install poetry
        run: pip install poetry

      - name: install dependencies
        run: |
          poetry install

      - name: run tests
        run: |
          poetry run pytest --cov=bot tests/

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      - name: build and push the docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy: 
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    if: github.ref == 'refs/heads/main'

    steps:
      - name: set up kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: deploy to kubernetes
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          helm upgrade --install kerhoff-reading-list-bot ./deploy/helm/kerhoff-reading-list-bot \
            --set image.repository=ghcr.io/${{ github.repository }} \
            --set image.tag=latest \
            --set env.DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --set env.TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}

