# Deploy to Managed Kubernetes
# This file is used to deploy the application to a managed Kubernetes cluster
# using the kubectl command line tool.

name: Deploy to Managed kubernetes

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl with Kebeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ~/.kube/config

      - name: Set up DOcker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Update image in Kubernetes manifest
        run: |
          sed -i "s|image: ghcr.io/.*/reading-bot:.*|image: ghcr.io/${{ github.repository_owner }}/reading-bot:latest|g" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Logout from GitHub Container Registry
        run: docker logout ghcr.io

