# Deploy to Managed Kubernetes
# This file is used to deploy the application to a managed Kubernetes cluster
# using the kubectl command line tool.
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml
          kubectl rollout status deployment/reading-bot
          kubectl get service reading-bot
